# Generated by Django 3.2.12 on 2023-04-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor',
            new_name='doctors',
        ),
    ]
